Repository yumis-coconudge/50k-web, pull requests merged in 2023-10, with the labels that each got.

#2 FTK-4 서비스 이용약관 동의 페이지 작업
  public/images/assets/common/around-location-active.svg
  public/images/assets/common/around-location.svg
  public/images/assets/common/article-active.svg
  public/images/assets/common/article.svg
  public/images/assets/common/chatting-active.svg
  public/images/assets/common/chatting.svg
  public/images/assets/common/check.svg
  public/images/assets/common/home-active.svg
  public/images/assets/common/home.svg
  public/images/assets/common/my-page-active.svg
  public/images/assets/common/my-page.svg
  src/pages/terms-of-use.tsx
Labels: 종류: 추가 🏗️, 형태: 작업 🚀

#1 [FTK-8] add navigation footer
  src/components/common/navigation-footer.tsx
Labels: 종류: 추가 🏗️, 형태: 작업 🚀

#6 [FTK-6] 프로필 작성하기 페이지 작업
  src/core/hooks/use-countdown.tsx
  src/pages/profile.tsx
Labels: 종류: 추가 🏗️, 형태: 작업 🚀

#7 [FTK-10] 공통 컴포너트 제작
  src/components/common/alert-provider.tsx
  src/components/common/option-provider.tsx
  src/components/common/popup-provider.tsx
  src/core/function/alert.ts
  src/core/function/option.ts
  src/core/hooks/use-outside-click.tsx
  src/core/hooks/use-popup.tsx
  src/pages/_app.tsx
  src/styles/globals.css
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#9 [FTK-14] 공지사항 리스트/상세 페이지 퍼블리싱
  package.json
  src/components/common/detail-layout.tsx
  src/components/common/header.tsx
  src/components/common/layout.tsx
  src/components/common/popover-image.tsx
  src/components/notice/list-card.tsx
  src/pages/_app.tsx
  src/pages/notice/[id].tsx
  src/pages/notice/index.tsx
  tailwind.config.js
  yarn.lock
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#10 [FTK-11] 메인페이지 퍼블리싱
  public/images/assets/common/un-check.svg
  src/components/common/header.tsx
  src/components/common/layout.tsx
  src/components/common/popup-provider.tsx
  src/components/common/select-popup.tsx
  src/components/index/category.tsx
  src/components/index/location-search.tsx
  src/components/index/meeting-list.tsx
  src/components/index/metting-card.tsx
  src/pages/index.tsx
  src/pages/notice/index.tsx
  tailwind.config.js
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#14 [FTK-34] 마이페이지 설정 퍼블리싱
  src/pages/mypage/setting.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#12 [FTK-78] footer 수정
  src/components/common/footer.tsx
  src/components/common/navigation-footer.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#13 [FTK-40]알림 설정 페이지 퍼블리싱
  src/components/common/toggle-switch.tsx
  src/pages/notification/setting.tsx
Labels: 🎨 퍼블리싱

#17 [FTK-30] 아티클 메인페이지(리스트) 퍼블리싱
  src/components/article/article-card.tsx
  src/core/hooks/use-is-visible.tsx
  src/pages/article/[id].tsx
  src/pages/article/index.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#20 [FTK-19] 반려동물 추가 페이지 작업
  public/images/assets/common/default-dog.svg
  public/images/assets/common/plus.svg
  public/images/assets/common/right.svg
  src/components/common/select-popup.tsx
  src/components/common/text-input.tsx
  src/components/common/textarea.tsx
  src/pages/add-pet/index.tsx
  src/pages/create-pet/index.tsx
  src/pages/pet-profile/index.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#18 [FTK-37] 1:1문의 작성/수정/상세/리스트 퍼블리싱 작업
  public/images/assets/common/kebab-menu.svg
  src/components/common/detail-page.tsx
  src/components/common/insert-image.tsx
  src/components/common/write-button.tsx
  src/components/common/write-modify.tsx
  src/components/inquiry/list-card.tsx
  src/pages/inquiry/[id].tsx
  src/pages/inquiry/index.tsx
  src/pages/inquiry/modify.tsx
  src/pages/inquiry/write.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#19 [FTK-41] 이용약관 페이지 퍼블리싱
  src/pages/policy/[id].tsx
  src/pages/policy/index.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#21 [FTK-27] 주변 탐색에 메인페이지 퍼블리싱
  package.json
  src/components/common/bottom-sheet.tsx
  src/components/common/footer.tsx
  src/components/common/layout.tsx
  src/components/location/shop-card.tsx
  src/core/hooks/use-bottom-sheet-behavior.tsx
  src/pages/article/[id].tsx
  src/pages/article/index.tsx
  src/pages/chat/index.tsx
  src/pages/location/index.tsx
  src/pages/my/index.tsx
  yarn.lock
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#22 [FTK-38] 계정관리 퍼블리싱
  src/pages/account/index.tsx
  src/pages/account/leave.tsx
  src/pages/account/phone-modify.tsx
  src/pages/my/setting.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#23 [FTK-79] 모임 참여 후 모임 메인페이지 퍼블리싱
  src/components/common/insert-image.tsx
  src/components/common/option-provider.tsx
  src/components/common/popover-image.tsx
  src/components/common/textarea.tsx
  src/components/common/write-modify.tsx
  src/components/index/meeting-card.tsx
  src/components/index/meeting-list.tsx
  src/components/meeting/board-card.tsx
  src/components/meeting/board-tab.tsx
  src/components/meeting/schedule-card.tsx
  src/core/function/option.ts
  src/pages/create-pet/index.tsx
  src/pages/meeting/board/[id].tsx
  src/pages/meeting/board/create.tsx
  src/pages/meeting/board/modify.tsx
  src/pages/meeting/index.tsx
  src/pages/meeting/schedule/[id].tsx
  src/pages/meeting/schedule/index.tsx
  src/pages/meeting/withdraw.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#25 [FTK-32] 마이페이지 작업
  public/images/assets/common/default-profile.svg
  public/images/assets/common/info-text.svg
  public/images/assets/common/menu.svg
  src/components/common/footer.tsx
  src/components/common/text-input.tsx
  src/components/meeting/board-card.tsx
  src/components/meeting/board-tab.tsx
  src/components/my/book-mark.tsx
  src/components/my/gathering.tsx
  src/components/my/post.tsx
  src/pages/my/index.tsx
  src/pages/my/profile-change.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱

#26 [FTK-42] 사용자 페이지 작업
  src/components/my/gathering.tsx
  src/pages/user/index.tsx
Labels: 종류: 추가 🏗️, 🎨 퍼블리싱, ⚙️ 프론트
